dag_populate_csv:
  default_args:
    owner: 'data_pipleline_oh'
    start_date: 2022-04-28
    retries: 1
    retry_delay_sec: 60
  description: 'this is an dag for populate csv!'
  default_view: 'tree'  # or 'graph', 'duration', 'gantt', 'landing_times'
  orientation: 'LR'  # or 'TB', 'RL', 'BT'
  schedule_interval: '@daily'
  catchp: False
  on_success_callback_name: on_success_teams
  on_success_callback_file:
  on_failure_callback_name: on_failure_teams
  on_failure_callback_file:
  tasks:
    task_export_csv:
      operator: airflow.operators.bash_operator.BashOperator
      bash_command: 'cd /home/airflow/gcs/dags/; python -m apps.populate_data_csv'

